# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x04serv\"\x1a\n\x0csell_request\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1c\n\rsell_response\x12\x0b\n\x03res\x18\x01 \x01(\x08\"\r\n\x0b\x62uy_request\"\x1a\n\x0c\x62uy_response\x12\n\n\x02id\x18\x01 \x01(\x05\x32k\n\nManagement\x12/\n\x04sell\x12\x12.serv.sell_request\x1a\x13.serv.sell_response\x12,\n\x03\x62uy\x12\x11.serv.buy_request\x1a\x12.serv.buy_responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SELL_REQUEST']._serialized_start=23
  _globals['_SELL_REQUEST']._serialized_end=49
  _globals['_SELL_RESPONSE']._serialized_start=51
  _globals['_SELL_RESPONSE']._serialized_end=79
  _globals['_BUY_REQUEST']._serialized_start=81
  _globals['_BUY_REQUEST']._serialized_end=94
  _globals['_BUY_RESPONSE']._serialized_start=96
  _globals['_BUY_RESPONSE']._serialized_end=122
  _globals['_MANAGEMENT']._serialized_start=124
  _globals['_MANAGEMENT']._serialized_end=231
# @@protoc_insertion_point(module_scope)
