# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hellosalerno_v2.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15hellosalerno_v2.proto\x12\x0fhellosalerno_v2\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\"\x19\n\nHelloReply\x12\x0b\n\x03msg\x18\x01 \x01(\t2\xa2\x01\n\x07Greeter\x12H\n\x08SayHello\x12\x1d.hellosalerno_v2.HelloRequest\x1a\x1b.hellosalerno_v2.HelloReply\"\x00\x12M\n\rSayHelloAgain\x12\x1d.hellosalerno_v2.HelloRequest\x1a\x1b.hellosalerno_v2.HelloReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hellosalerno_v2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=42
  _globals['_HELLOREQUEST']._serialized_end=70
  _globals['_HELLOREPLY']._serialized_start=72
  _globals['_HELLOREPLY']._serialized_end=97
  _globals['_GREETER']._serialized_start=100
  _globals['_GREETER']._serialized_end=262
# @@protoc_insertion_point(module_scope)
