# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistics.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10statistics.proto\x12\nstatistics\"\x07\n\x05\x45mpty\")\n\x07Sensors\x12\x0b\n\x03_id\x18\x01 \x01(\x03\x12\x11\n\tdata_type\x18\x02 \x01(\t\"4\n\x0cMean_Request\x12\x11\n\tsensor_id\x18\x01 \x01(\x03\x12\x11\n\tdata_type\x18\x02 \x01(\t\"\x1d\n\rStringMessage\x12\x0c\n\x04mean\x18\x01 \x01(\t2\x85\x01\n\nstatistics\x12\x36\n\nget_sensor\x12\x11.statistics.Empty\x1a\x13.statistics.Sensors0\x01\x12?\n\x08get_mean\x12\x18.statistics.Mean_Request\x1a\x19.statistics.StringMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statistics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=32
  _globals['_EMPTY']._serialized_end=39
  _globals['_SENSORS']._serialized_start=41
  _globals['_SENSORS']._serialized_end=82
  _globals['_MEAN_REQUEST']._serialized_start=84
  _globals['_MEAN_REQUEST']._serialized_end=136
  _globals['_STRINGMESSAGE']._serialized_start=138
  _globals['_STRINGMESSAGE']._serialized_end=167
  _globals['_STATISTICS']._serialized_start=170
  _globals['_STATISTICS']._serialized_end=303
# @@protoc_insertion_point(module_scope)
